spring:
  application:
    name: ccip-patient
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ccip_patient?serverTimezone=GMT%2B8
    username: root
    password: admin
server: 
  port: 8081

eureka: 
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka

mybatis:
  mapperLocations: classpath:mapping/*.xml
  configuration:
    mapUnderscoreToCamelCase: true